---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controllers/metallb
  - controllers/cert-manager
  - controllers/gateway-api
  - controllers/nginx-gateway
  # - networking
  # - storage
